### ISSUE TITLE
[功能]: 子路由下面的roles 如果一个都不匹配的时候 会报错，

### ISSUE THREAD

**Issue by hslsh2297** [soybeanjs/soybean-admin-react#17]
### 描述

{
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
    },
    children: [
      {
        name: 'manage_menu',
        path: 'menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_SUPER'],
        }
      },
      {
        name: 'manage_role',
        path: 'role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: 'user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: 'user-detail/:id',
        component: 'view.manage_user-detail',
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },

### 建议的解决方案

1

### 额外的上下文

![Snipaste_2024-10-27_23-31-30](https://github.com/user-attachments/assets/85215067-a75a-40b0-b629-e5f43762c3a5)

**Comment by mufeng889** [comment]
您好 我并没有复现出来你的问题
